services: 
  url-shortener:
    image: codeberg.org/lezurex/url-shortener:latest # <= RECOMMENDED: change to fixed version
    volumes:
      - data:/var/www/html/data:rw
    ports:
    - "8080:8080"

volumes:
  data:
